name: EAS BUILD and Firebase Upload

on:
  push:
    branches:
      - development
jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name : Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: EAS login
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 🧪 Build APK using EAS (wait for completion)
        id: eas-build
        run: |
            result=$(eas build --platform android --profile development --non-interactive --wait --json)
            echo "$result"
            
            # Extract the download URL
            url=$(echo "$result" | jq -r '.artifacts.android.url')
            echo "APK download URL: $url"
            echo "APK_URL=$url" >> $GITHUB_ENV
          env:
            EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: 📥 Download APK
        run: curl -o app-release.apk "$APK_URL"

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          file: app-release.apk
          groups: testers